name: hotelmanagementapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  flutter_inappwebview: ^5.7.2+3
  after_layout: ^1.2.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/profileImage.svg
    - assets/
    - assets/search-normal.svg
    - assets/images/interaction.png
    - assets/images/faq.png
    - assets/images/approval.png
    - assets/images/round_play.png
    - assets/images/bottomIS.png

  # fonts:
  #   - family: Inter
  #     fonts:
        # - asset: fonts/Schyler-Regular.ttf
        # - asset: fonts/Schyler-Italic.ttf
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
