// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWDZkn03gGxw7jnJYSQI0PZQbSTY8LC1Q',
    appId: '1:233565329277:web:eb0011844adb7e25005e14',
    messagingSenderId: '233565329277',
    projectId: 'hotel-management-app-d25d5',
    authDomain: 'hotel-management-app-d25d5.firebaseapp.com',
    storageBucket: 'hotel-management-app-d25d5.firebasestorage.app',
    measurementId: 'G-7ZKCWWK72K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ04znTLuHChNJgP99sIFVRoe9CJoS5Ao',
    appId: '1:233565329277:android:42d9d7888d650fd6005e14',
    messagingSenderId: '233565329277',
    projectId: 'hotel-management-app-d25d5',
    storageBucket: 'hotel-management-app-d25d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz975uIxl_YJbNLrn7pUM9sTxUHck56SY',
    appId: '1:233565329277:ios:e529ad74eb093435005e14',
    messagingSenderId: '233565329277',
    projectId: 'hotel-management-app-d25d5',
    storageBucket: 'hotel-management-app-d25d5.firebasestorage.app',
    iosBundleId: 'com.example.hotelmanagementapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz975uIxl_YJbNLrn7pUM9sTxUHck56SY',
    appId: '1:233565329277:ios:e529ad74eb093435005e14',
    messagingSenderId: '233565329277',
    projectId: 'hotel-management-app-d25d5',
    storageBucket: 'hotel-management-app-d25d5.firebasestorage.app',
    iosBundleId: 'com.example.hotelmanagementapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWDZkn03gGxw7jnJYSQI0PZQbSTY8LC1Q',
    appId: '1:233565329277:web:4df00d8ac94bf7ff005e14',
    messagingSenderId: '233565329277',
    projectId: 'hotel-management-app-d25d5',
    authDomain: 'hotel-management-app-d25d5.firebaseapp.com',
    storageBucket: 'hotel-management-app-d25d5.firebasestorage.app',
    measurementId: 'G-TTRVND8795',
  );
}
